name: test_suite_flutter
description: A Test Suite for Expo Modules on Flutter.


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

  expo_flutter_adapter: ^0.1.0

  expo_permissions: ^0.1.0

  expo_sensors: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

dependency_overrides:
  expo_flutter_adapter:
      path: ../../expo-flutter-adapter

  expo_permissions:
    path: ../../expo-permissions-flutter-plugin

  expo_sensors:
    path: ../../expo-sensors-flutter-plugin

