name: expo_nativescript_adapter
description: A plugin that enables the usage of Expo Universal Modules in Flutter.
version: 0.1.1
authors:
  - Juwan Wheatley <juwan@expo.io>
  - Nikhilesh Sigatapu <nikki@expo.io>
  - Jamie Birch <14055146+shirakaba@users.noreply.github.com>
homepage: https://github.com/expo/expo/tree/master/packages/expo-nativescript-adapter

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  nativescript:
    sdk: nativescript

dev_dependencies:
  expo_permissions: ^0.1.0
  expo_sensors: ^0.1.0

nativescript:
  plugin:
    androidPackage: io.expo.exponativescriptadapter
    pluginClass: ExpoFlutterAdapterPlugin
