name: expo_flutter_adapter
description: A plugin that enables the usage of Expo Universal Modules in Flutter.
version: 0.1.1
authors:
  - Juwan Wheatley <juwan@expo.io>
  - Nikhilesh Sigatapu <nikki@expo.io>
homepage: https://github.com/expo/expo/tree/master/packages/expo-flutter-adapter

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  expo_permissions: ^0.1.0
  expo_sensors: ^0.1.0

flutter:
  plugin:
    androidPackage: io.expo.expoflutteradapter
    pluginClass: ExpoFlutterAdapterPlugin
